# Generated by Django 3.1 on 2020-08-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_course_abc_to_mti'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseOld',
        ),
    ]
